import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '../styles/Home.module.css'
import { useRouter } from "next/router";
import React, {useEffect, useState} from 'react'
import WebsiteMovie from '../components/WebsiteMovie';
import NavBar from '../components/NavBar';

const inter = Inter({ subsets: ['latin'] })



export default function Home() {

  const router = useRouter();
  const [connectedUser, setConnectedUser] = useState(undefined);
  const [movies, setMovies] = useState(undefined);

  

  async function getLocalStorageToken() {
    const now = new Date().getTime();
    const token = JSON.parse(localStorage.getItem("access_token"));
    if (!token) {
        console.log("User is not logged in");
        setConnectedUser(undefined);
        return;
    } else {
        if (now > token.expiry) {
            localStorage.removeItem("access_token");
            this.connectedUser = undefined;
        } else {
            console.log("user is logged in");
            const response = await fetch('http://localhost:3002/usersWithToken/' + token.access_token)
                .then(response => response.json())
            setConnectedUser(response);
        }
    }
  }

  async function getMovies(){
    const response = await fetch('http://localhost:3002/movies')  
      .then((response) => response.json());
    setMovies(response);
  }

  useEffect(() => {
    getLocalStorageToken();
    getMovies();
    localStorage.removeItem('movie_id');
    localStorage.removeItem('user_to_update');
  }, [])

  return (

    <div>
      <Head>
        <title>Rotten Tomato</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavBar/>
      <body className='body_bg'>
        <main className={styles.main}>
          <div className='website_movie'>
            {movies ? movies.map(movie => <WebsiteMovie movie={movie} />) : <p>Loading..</p>}
          </div>
        </main>
      </body>
    </div>
  )
}
